#[path = "src/contracts.rs"]
mod contracts;

use std::fs;
use std::path::PathBuf;
use ts_rs::TS;

fn exported(declaration: String) -> String {
    declaration.replacen("type ", "export type ", 1)
}

fn main() {
    println!("cargo:rerun-if-changed=src/contracts.rs");
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap_or_default());
    let Some(frontend_root) = manifest.parent() else {
        panic!("Tauri manifest has no frontend parent");
    };
    let output = frontend_root.join("src/api/generated.ts");
    let mut text = String::from("/* @generated by src-tauri/build.rs; do not edit. */\n");
    text.push_str(&exported(contracts::SettingsDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::PlanRequestDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::PlanItemDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::PlanResponseDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::BootstrapDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::AppSettingsDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::ApiErrorDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::QueueProgressDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::QueueItemResultDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::QueueItemDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::QueueMetricsDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::QueueStateDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::QueueSnapshotDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::ActivityEventDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::QueueStreamMessage::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::PreviewOptionsDto::decl()));
    text.push('\n');
    text.push_str(&exported(contracts::PreviewResultDto::decl()));
    text.push_str("\nexport type Codec = SettingsDto['codec'];\nexport type EncoderBackend = SettingsDto['backend'];\nexport type DecodeAcceleration = SettingsDto['decodeAcceleration'];\nexport type ContainerFormat = SettingsDto['container'];\nexport type AudioMode = SettingsDto['audioMode'];\n");
    if let Err(error) = fs::write(output, text) {
        panic!("cannot write generated TypeScript bindings: {error}");
    }
    tauri_build::build();
}
