#!/usr/bin/env python3
"""Validate Tauri bundle resources and generated frontend output."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "apps" / "desktop" / "src-tauri" / "tauri.conf.json"


def fail(message: str) -> int:
    print(f"tauri resource check failed: {message}", file=sys.stderr)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--require-frontend-dist",
        action="store_true",
        help="fail when build.frontendDist has not been built yet",
    )
    args = parser.parse_args()
    try:
        config = json.loads(CONFIG.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        return fail(f"cannot read {CONFIG}: {error}")

    config_root = CONFIG.parent
    bundle = config.get("bundle", {})
    for relative in bundle.get("icon", []):
        path = config_root / relative
        if not path.is_file():
            return fail(f"missing icon declared by Tauri config: {path}")
    for relative in bundle.get("resources", []):
        path = config_root / relative
        if not path.exists():
            return fail(f"missing resource declared by Tauri config: {path}")

    frontend_dist = config_root / config.get("build", {}).get("frontendDist", "")
    if not frontend_dist.exists():
        package_json = ROOT / "apps" / "desktop" / "package.json"
        try:
            package = json.loads(package_json.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            return fail(f"cannot inspect frontend build script: {error}")
        build_script = package.get("scripts", {}).get("build", "")
        if args.require_frontend_dist or not build_script:
            return fail(f"frontendDist does not exist and cannot be generated: {frontend_dist}")
        print(f"frontendDist will be generated by package build: {frontend_dist}")

    print("Tauri resource check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
